export const CATEGORY_OPTIONS = [
  { label: "Venues", value: "venues" },
  { label: "Gurdwaras", value: "gurdwaras" },
  { label: "Catering", value: "catering" },
  { label: "Photography", value: "photography" },
  { label: "Videography", value: "videography" },
  { label: "Bartending Services", value: "bartending services" },
  { label: "Invitations", value: "invitations" },
  { label: "Wedding Planners", value: "wedding planners" },
  { label: "Music & DJs", value: "music & djs" },
  { label: "Wedding Cakes", value: "wedding cakes" },
  { label: "Wedding Wardrobe & Jewelry", value: "wedding wardrobe & jewelry" },
  { label: "Event Rentals & Decor", value: "event rentals & decor" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Transportation", value: "transportation" },
  { label: "Flowers", value: "flowers" },
  { label: "Hair & Makeup Artists", value: "hair & makeup artists" },
  { label: "Mehndi Artists", value: "mehndi artists" },
  { label: "Wedding Favours", value: "wedding favours" },
  { label: "Maiyan Boards", value: "maiyan boards" },
];

export const PriceRange = [
  { label: "$0 - $500", value: 0 },
  { label: "$500 - $1,000", value: 500 },
  { label: "$1,000 - $2,500", value: 1000 },
  { label: "$2,500 - $5,000", value: 2500 },
  { label: "$5,000 - $10,000", value: 5000 },
  { label: "$10,000 - $20,000", value: 10000 },
  { label: "$20,000 - $50,000", value: 20000 },
  { label: "$50,000+", value: 50000 },
];
